GET /api/plugin/autoprint
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB


POST /api/plugin/autoprint
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB
Content-Type: application/json
{
    "command" : "startUpPrinter"
}

POST /api/plugin/autoprint
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB
Content-Type: application/json
{
    "command" : "shutDownPrinter"
}


POST /api/plugin/autoprint
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB
Content-Type: application/json
{
    "command" : "toggleLight"
}

POST /api/plugin/autoprint
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB
Content-Type: application/json
{
    "file":"test.gcode",
    "time":1654717428702,
    "turnOffAfterPrint":false,
    "startFinish":"finish",
    "command":"scheduleJob"
}

GET /api/files/local/autoprint/test.gcode   
Host: localhost:1885
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB
