GET /api/plugin/autoprint?state
Host: localhost:1880
X-Api-Key: AFC41060514F4909A15B6BCF84B3D6FB


POST /api/plugin/gpiocontrol
Host: octopi.local
X-Api-Key: 5BAC3004BC394F73A2E20580E3967D12
Content-Type: application/json
{
    "command" : "getGpioState",
    "id" : 1
}

POST /api/plugin/gpiocontrol
Host: octopi.local
X-Api-Key: 5BAC3004BC394F73A2E20580E3967D12
Content-Type: application/json
{
    "command" : "turnGpioOn",
    "id" : 1
}

GET /api/plugin/gpiocontrol
Host: 10.0.1.219
X-Api-Key: 5BAC3004BC394F73A2E20580E3967D12

vWUXg70g8v60vkoYuyLB9eAMZ3AocfYv9b/QD33c